// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv9IU9ANIBWmKT0AoptFYGGqr4WEUyvaw',
    appId: '1:751244806919:web:488c0f539f090fac3413a2',
    messagingSenderId: '751244806919',
    projectId: 'rogue-journeys',
    authDomain: 'rogue-journeys.firebaseapp.com',
    storageBucket: 'rogue-journeys.firebasestorage.app',
    measurementId: 'G-L0BLCNTZ9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtFziJuozgHoFeQgX_UYJUbY5r-51loqA',
    appId: '1:751244806919:android:31f6944ec38a37c73413a2',
    messagingSenderId: '751244806919',
    projectId: 'rogue-journeys',
    storageBucket: 'rogue-journeys.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9kANYBin8s0TlKm5dADvbhS1mES55YqE',
    appId: '1:751244806919:ios:129ff4743e50cada3413a2',
    messagingSenderId: '751244806919',
    projectId: 'rogue-journeys',
    storageBucket: 'rogue-journeys.firebasestorage.app',
    iosBundleId: 'com.example.rogueJourneys',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9kANYBin8s0TlKm5dADvbhS1mES55YqE',
    appId: '1:751244806919:ios:129ff4743e50cada3413a2',
    messagingSenderId: '751244806919',
    projectId: 'rogue-journeys',
    storageBucket: 'rogue-journeys.firebasestorage.app',
    iosBundleId: 'com.example.rogueJourneys',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAv9IU9ANIBWmKT0AoptFYGGqr4WEUyvaw',
    appId: '1:751244806919:web:dac5ddb08f7f8bf13413a2',
    messagingSenderId: '751244806919',
    projectId: 'rogue-journeys',
    authDomain: 'rogue-journeys.firebaseapp.com',
    storageBucket: 'rogue-journeys.firebasestorage.app',
    measurementId: 'G-S8L70VF6HF',
  );

}